class ConstDefine:
    """
    공통 상수 정의 클래스
    프로젝트 전체에서 사용할 상수를 이곳에 정의하세요.
    """

    # 예시 상수
    ON = 1
    OFF = 0

    # 파일 및 디렉토리 경로 예시
    CONFIG_PATH = '/home/pi/Projects/cosmo-m/config/config.ini'
    DEFAULT_REF_DIR = '/home/pi/Projects/cosmo-m/ref/'

    # 기타 예시 상수 (필요에 따라 추가)
    DEFAULT_SETPOINT = 15.0
    DEFAULT_KP = 1.0
    DEFAULT_KI = 0.5
    DEFAULT_KD = 0.1

    # 타이머 관련 상수
    PID_TIMER_INTERVAL = 0.1  # seconds
    TIMER_TASK_INTERVAL = 1.0  # seconds

    # 유닛 상태
    STATE_RUN = 'Run'
    STATE_PAUSE = 'Pause'
    STATE_STOP = 'Stop'

    # 기타 필요한 상수는 프로젝트 진행하며 추가하여 사용하세요.

    # 공유 메모리 오프셋
    SHARED_MEMORY_OFFSET_PID = 0x00
    SHARED_MEMORY_OFFSET_ADC1 = 0x01
    SHARED_MEMORY_OFFSET_ADC2 = 0x02
    SHARED_MEMORY_OFFSET_ADC3 = 0x03
    SHARED_MEMORY_OFFSET_ADC4 = 0x04
    SHARED_MEMORY_OFFSET_ADC5 = 0x05
    SHARED_MEMORY_OFFSET_ADC6 = 0x06
    SHARED_MEMORY_OFFSET_ADC7 = 0x07
    SHARED_MEMORY_OFFSET_ADC8 = 0x08
    SHARED_MEMORY_OFFSET_ADC_RAW1 = 0x09
    SHARED_MEMORY_OFFSET_ADC_RAW2 = 0x0A
    SHARED_MEMORY_OFFSET_ADC_TEMP1 = 0x0B
    SHARED_MEMORY_OFFSET_ADC_TEMP2 = 0x0C
    SHARED_MEMORY_OFFSET_ADC_TEMP3 = 0x0D
    SHARED_MEMORY_OFFSET_ADC_TEMP4 = 0x0E
    SHARED_MEMORY_OFFSET_ADC_TEMP5 = 0x0F
    SHARED_MEMORY_OFFSET_ADC_TEMP6 = 0x10
    SHARED_MEMORY_OFFSET_ADC_TEMP7 = 0x11
    SHARED_MEMORY_OFFSET_ADC_TEMP8 = 0x12
    SHARED_MEMORY_OFFSET_ADC_RAW_TEMP1 = 0x13
    SHARED_MEMORY_OFFSET_ADC_RAW_TEMP2 = 0x14
    SHARED_MEMORY_OFFSET_RESERVED1 = 0x15
    SHARED_MEMORY_OFFSET_RESERVED2 = 0x16
    SHARED_MEMORY_OFFSET_INDEX = 0x17
    SHARED_MEMORY_OFFSET_STATE = 0x18
    SHARED_MEMORY_OFFSET_RESERVED3 = 0x19
    SHARED_MEMORY_OFFSET_GPO0_7= 0x1A
    SHARED_MEMORY_OFFSET_RESERVED4 = 0x1B
    SHARED_MEMORY_OFFSET_GPI0_7= 0x1C
    SHARED_MEMORY_OFFSET_RESERVED5 = 0x1D
    SHARED_MEMORY_OFFSET_INVERTER_STATUS = 0x1E
    SHARED_MEMORY_OFFSET_RESERVED6 = 0x1F
    SHARED_MEMORY_OFFSET_RESERVED7 = 0x20
    SHARED_MEMORY_OFFSET_RESERVED8 = 0x21
    SHARED_MEMORY_OFFSET_RESERVED9 = 0x22
    SHARED_MEMORY_OFFSET_RPM = 0x23
    SHARED_MEMORY_OFFSET_LOAD_CELL = 0x24
    SHARED_MEMORY_OFFSET_BRIX = 0x25
    SHARED_MEMORY_OFFSET_CO2 = 0x26
    SHARED_MEMORY_OFFSET_FLOWER = 0x27
    SHARED_MEMORY_OFFSET_PH1 = 0x28
    SHARED_MEMORY_OFFSET_PH2 = 0x29
    SHARED_MEMORY_OFFSET_PH3 = 0x2A
    SHARED_MEMORY_OFFSET_PH4 = 0x2B
    SHARED_MEMORY_OFFSET_ERROR_CODE = 0x2C
    SHARED_MEMORY_OFFSET_EXT_TEMP = 0x2D
    SHARED_MEMORY_OFFSET_EXT_HUMI = 0x2E
    # 공유 메모리 마지막 부터 시작 되는 옵셋
    SHARED_MEMORY_OFFSET_WATER_MOTOR = 0x00
    SHARED_MEMORY_OFFSET_CHILLER1_MOTOR = 0x01 
    SHARED_MEMORY_OFFSET_CHILLER2_MOTOR = 0x02 


    SET_CONFIG_COMMAND = 0x01
    GET_STATUS_COMMAND = 0x02
    GET_ADC_COMMAND = 0x03
    GET_GPIO_COMMAND = 0x04
    SET_GPIO_COMMAND = 0x05
    SET_MOTOR_COMMAND = 0x06
    TEMP_RPM_COMMAND = 0x07
    TEMP_VALVE_COMMAND = 0x08
    WEIGHT_VALVE_COMMAND = 0x09
    GET_VERSION_COMMAND = 0x0A
    BOOT_UNIT_BOARD_COMMAND = 0x0B
    ADC_CALIBRATION_COMMAND = 0x0C
    LOADCELL_ZERO_COMMAND = 0x0D
    SET_GPIO_EX_COMMAND = 0x0E
    PING_UNIT_BOARD_COMMAND = 0x0F
    HOLD_TX_COMMAND = 0x10
    FIRMWARE_UPDATE_COMMAND = 0xFE
    
    ERROR_CODE_OK = 0
    ERROR_CODE_COMMUNICATION = 10
    ERROR_CODE_ENCODER1 = 11
    ERROR_CODE_ENCODER2 = 12
    ERROR_CODE_ENCODER3 = 13
    ERROR_CODE_ENCODER4 = 14
    ERROR_CODE_ENCODER5 = 15
    ERROR_CODE_ENCODER6 = 16
    ERROR_CODE_ENCODER7 = 17
    ERROR_CODE_ENCODER8 = 18
    ERROR_CODE_RS485_1 = 19
    ERROR_CODE_RS485_2 = 20
    ERROR_CODE_RS485_3 = 21
    ERROR_CODE_RS485_4 = 22
    ERROR_CODE_RS232_1 = 23
    ERROR_CODE_INVERTER = 24
    ERROR_CODE_LOAD_CELL = 25
    ERROR_CODE_PH_SENSOR = 26
    ERROR_CODE_CO2_SENSOR = 27
    ERROR_CODE_FLOWER_SENSOR = 28
    ERROR_CODE_TEMP_SENSOR = 29