class ConstDefine:
    """
    공통 상수 정의 클래스
    프로젝트 전체에서 사용할 상수를 이곳에 정의하세요.
    """

    # 예시 상수
    ON = 1
    OFF = 0

    # 파일 및 디렉토리 경로 예시
    CONFIG_PATH = '/home/pi/Projects/cosmo-m/config/config.ini'
    DEFAULT_REF_DIR = '/home/pi/Projects/cosmo-m/ref/'

    # 기타 예시 상수 (필요에 따라 추가)
    DEFAULT_SETPOINT = 15.0
    DEFAULT_KP = 1.0
    DEFAULT_KI = 0.5
    DEFAULT_KD = 0.1

    # 타이머 관련 상수
    PID_TIMER_INTERVAL = 0.1  # seconds
    TIMER_TASK_INTERVAL = 1.0  # seconds

    # 유닛 상태
    STATE_RUN = 'Run'
    STATE_PAUSE = 'Pause'
    STATE_STOP = 'Stop'

    # 기타 필요한 상수는 프로젝트 진행하며 추가하여 사용하세요.

    # 공유 메모리 오프셋
    SHARED_MEMORY_OFFSET_PID = 0x00
    SHARED_MEMORY_OFFSET_ADC1 = 0x01
    SHARED_MEMORY_OFFSET_ADC2 = 0x02
    SHARED_MEMORY_OFFSET_ADC3 = 0x03
    SHARED_MEMORY_OFFSET_ADC4 = 0x04
    SHARED_MEMORY_OFFSET_ADC5 = 0x05
    SHARED_MEMORY_OFFSET_ADC6 = 0x06
    SHARED_MEMORY_OFFSET_ADC7 = 0x07
    SHARED_MEMORY_OFFSET_ADC8 = 0x08
    SHARED_MEMORY_OFFSET_ADC_RAW1 = 0x09
    SHARED_MEMORY_OFFSET_ADC_RAW2 = 0x0A
    SHARED_MEMORY_OFFSET_ADC_TEMP1 = 0x0B
    SHARED_MEMORY_OFFSET_ADC_TEMP2 = 0x0C
    SHARED_MEMORY_OFFSET_ADC_TEMP3 = 0x0D
    SHARED_MEMORY_OFFSET_ADC_TEMP4 = 0x0E
    SHARED_MEMORY_OFFSET_ADC_TEMP5 = 0x0F
    SHARED_MEMORY_OFFSET_ADC_TEMP6 = 0x10
    SHARED_MEMORY_OFFSET_ADC_TEMP7 = 0x11
    SHARED_MEMORY_OFFSET_ADC_TEMP8 = 0x12
    SHARED_MEMORY_OFFSET_ADC_RAW_TEMP1 = 0x13
    SHARED_MEMORY_OFFSET_ADC_RAW_TEMP2 = 0x14
    SHARED_MEMORY_OFFSET_RESERVED1 = 0x15
    SHARED_MEMORY_OFFSET_RESERVED2 = 0x16
    SHARED_MEMORY_OFFSET_INDEX = 0x17
    SHARED_MEMORY_OFFSET_STATE = 0x18
    SHARED_MEMORY_OFFSET_RESERVED3 = 0x19
    SHARED_MEMORY_OFFSET_GPO0_7= 0x1A
    SHARED_MEMORY_OFFSET_RESERVED4 = 0x1B
    SHARED_MEMORY_OFFSET_GPI0_7= 0x1C
    SHARED_MEMORY_OFFSET_RESERVED5 = 0x1D
    SHARED_MEMORY_OFFSET_INVERTER_STATUS = 0x1E
    SHARED_MEMORY_OFFSET_RESERVED6 = 0x1F
    SHARED_MEMORY_OFFSET_RESERVED7 = 0x20
    SHARED_MEMORY_OFFSET_RESERVED8 = 0x21
    SHARED_MEMORY_OFFSET_RESERVED9 = 0x22
    SHARED_MEMORY_OFFSET_RPM = 0x23
    SHARED_MEMORY_OFFSET_LOAD_CELL = 0x24
    SHARED_MEMORY_OFFSET_BRIX = 0x25
    SHARED_MEMORY_OFFSET_CO2 = 0x26
    SHARED_MEMORY_OFFSET_FLOWER = 0x27
    SHARED_MEMORY_OFFSET_PH = 0x28
    SHARED_MEMORY_OFFSET_ERROR_CODE = 0x29
    SET_CONFIG_COMMAND = 0x01
    GET_STATUS_COMMAND = 0x02
    GET_ADC_COMMAND = 0x03
    GET_GPIO_COMMAND = 0x04
    SET_GPIO_COMMAND = 0x05
    SET_MOTOR_COMMAND = 0x06
    TEMP_RPM_COMMAND = 0x07
    TEMP_VALVE_COMMAND = 0x08
    WEIGHT_VALVE_COMMAND = 0x09
    GET_VERSION_COMMAND = 0x0A
    BOOT_UNIT_BOARD_COMMAND = 0x0B
    FIRMWARE_UPDATE_COMMAND = 0xFE
    
